### ISSUE TITLE
Prepare standalone native CKB node to run test cases of `spore-sdk` from a same genesis status

### ISSUE THREAD

**Issue by ashuralyk** [sporeprotocol/spore-scrum#2]
# Description
currently, `spore-sdk` runs its test cases directly in CKB testnet, which can lead to the failure of test due to the on-chain state transfer. To solve it, we should prepare a standalone native CKB node running in the GitHub CI/CD environment to ensure the on-chain state equality

# Tasks list
- [x] prepare simulator of CKB native node which is already integrated the latest Spore contracts
https://github.com/Dawn-githup/CKB-Contract-Data-Simulator
- [x] integrate simulator into `spore-sdk` CI yaml file
https://github.com/sporeprotocol/spore-sdk/pull/48
- [x] successfully pass the process of `spore-sdk` CI/CD test

**Comment by ashuralyk** [comment]
devnet repo has moved to spore org: https://github.com/sporeprotocol/spore-devenv
