### ISSUE TITLE
Focus on Nervos DAO migration of CKB mainnet publish proposal from Nervos talk

### ISSUE THREAD

**Issue by ashuralyk** [sporeprotocol/spore-scrum#6]
# Description
we have announced the mainnet publish event of Spore project, now we are almost at the Nervos DAO proposal step after if touching 20 likes from the Nervos talk community

the next step is to confirm a concrete migration date of project Spore for our community

p.s. proposal link: https://talk.nervos.org/t/dis-spore-protocol-mainnet-launch-sponsorship-proposal-spore-protocol/7593/1

# Tasks list
- [x] confirm if our current situation is ready for us to start our mainnet migration
- [x] estimate how long should we take to approach the migration event (until 20 Jan)
- [x] determine the final release date of Spore
- [x] discuss how to gather our 100K initial CKB to stake in Nervos DAO after the migration operation is confirmed (already received)

**Comment by ashuralyk** [comment]
co-build integration has finished its test among contract and sdk, primary condition of mainnet launch has been reached, but thinking of we've got a little room to wait the testing of spore demo finished, so I recommend we hold mainnet launch until demo gets ready

**Comment by ashuralyk** [comment]
# Prerequisites of Mainnet Deployment

- [x] freeze `spore-contract` version **v0.2.0** (commit hash: [b97831a93b59cbd720441b48cd2bb42dc87cbe9f](https://github.com/sporeprotocol/spore-contract/commit/b97831a93b59cbd720441b48cd2bb42dc87cbe9f))
- [x] pass all of test cases in `spore-sdk` of version **v0.2.0-beta.1** (commit hash: [6c5734157cc5efd96faf610b731e35d22afab06c](https://github.com/sporeprotocol/spore-sdk/commit/6c5734157cc5efd96faf610b731e35d22afab06c))
- [x] upgrade `spore-graphql` to support `spore-sdk` of version **v0.2.0-beta.1**
- [x] `philosopher stone` works fine under `spore-sdk` version **v0.2.0-beta.1**

# Better User Experience of Mainnet Launch

- [x] release `spore-contract` deployment information under version **v0.2.2-beta.1**
- [x] release `spore-sdk` versions until and including **v0.2.0-beta.2**
- [x] official doc update
- [x] update Spore logo in explorer
- [x] nervous talk update

----
cc @RongxinZhang @Flouse @ShookLyngs @Dawn-githup @lee920217
